### ISSUE TITLE
Move to stat447 ?

### ISSUE THREAD

**Issue by eddelbuettel** [stat447/plr#2]
Now that 'stat430dspm' is "history", should this move to the new stat447 org?  

_Edit_ Typo fixed.

**Comment by barbehenna** [comment]
Sure, ~~I think the new number is 447 though~~

**Comment by eddelbuettel** [comment]
Indeed. Sloppy typing on my part as usual.  Should have asked for 444 :grimacing:

**Comment by eddelbuettel** [comment]
That has been done.
